### PR TITLE
Hide passwords in repo path, fixing #58

### PR DESCRIPTION
**Pull request by nettnikl**

### CODE REVIEW

**Comment by emuell** [comment]
Thanks for the contribution!

As the regex only applies to REST paths, I would move the regex replacement code into an `if (appState.repoLocation.prefix == "rest")` branch, also to document what it's trying to match. 

The regex also won't match rest paths of the form `https://user:pass@host:8000` (note the missing trailing /), but I'm not actually sure if restic allows them. But it won't match sftp path then either?

**Comment by nettnikl** [comment]
I didn't think about ports, will habe to check. But you're right i'm missing quite a few test cases. Thin i was focusing on here wasmainly that we can have the protocol optional in the URL (diallowing the URL() from js).
Let's collect all cases interesting to blur out here, and then adjust.

**Comment by nettnikl** [comment]
I actually tried to design it to work with any URL, rest but also sftp, ftps or any future URL like path. Ports and the whole path after the domain are now more leniently handled. Care to have a look?

**Comment by emuell** [comment]
Looks good to me. Thanks!

**Pull request merged**
